-- Compound cloud sync — database schema.
--
-- The schema now lives in versioned migrations under supabase/migrations/.
-- Each one is idempotent and creates what it needs from scratch, so:
--
--   * a NEW project: run every file in supabase/migrations/ in name order
--     (SQL editor, or `supabase db push`);
--   * an EXISTING project set up from the old version of this file: run the
--     same files — they upgrade it in place without touching user data.
--
-- After running them, apply the dashboard settings listed in
-- docs/security.md (password rules, leaked-password check, MFA, secure
-- password change, redirect allow-list). Those live in Auth config, not SQL.
