// Generated manifest for the font library picker (see fontlib.css).
// Font binaries are local-only; if one is missing the browser simply
// falls back, so a clone of the repo still works.
export interface LibFont { label: string; family: string }

export const FONT_LIBRARY: LibFont[] = [
  { label: "Aachen Std", family: "lib Aachen Std" },
  { label: "Adobe Caslon Pro", family: "lib Adobe Caslon Pro" },
  { label: "Adobe Garamond Pro", family: "lib Adobe Garamond Pro" },
  { label: "Adobe Jenson Pro", family: "lib Adobe Jenson Pro" },
  { label: "Adobe Wood Type Ornaments Std", family: "lib Adobe Wood Type Ornaments Std" },
  { label: "Albertus MT Std", family: "lib Albertus MT Std" },
  { label: "Aldus LT Std", family: "lib Aldus LT Std" },
  { label: "Alexa Std", family: "lib Alexa Std" },
  { label: "Americana Std", family: "lib Americana Std" },
  { label: "Andreas Std", family: "lib Andreas Std" },
  { label: "Antique Olive Std", family: "lib Antique Olive Std" },
  { label: "Apollo MT Std", family: "lib Apollo MT Std" },
  { label: "Arcadia LT Std", family: "lib Arcadia LT Std" },
  { label: "Arcana GMM Std", family: "lib Arcana GMM Std" },
  { label: "Ariadne LT Std", family: "lib Ariadne LT Std" },
  { label: "Arial Rounded", family: "lib Arial Rounded" },
  { label: "Arnold Boecklin Std", family: "lib Arnold Boecklin Std" },
  { label: "Ashley Script MT Std", family: "lib Ashley Script MT Std" },
  { label: "Auriol LT Std", family: "lib Auriol LT Std" },
  { label: "Avenir LT Std", family: "lib Avenir LT Std" },
  { label: "Balzano Std", family: "lib Balzano Std" },
  { label: "Banco Std", family: "lib Banco Std" },
  { label: "Banshee Std", family: "lib Banshee Std" },
  { label: "Baskerville Cyrillic LT Std", family: "lib Baskerville Cyrillic LT Std" },
  { label: "Bauer Bodoni Std", family: "lib Bauer Bodoni Std" },
  { label: "Bauhaus Std", family: "lib Bauhaus Std" },
  { label: "Bell Centennial Std", family: "lib Bell Centennial Std" },
  { label: "Bell Gothic Std", family: "lib Bell Gothic Std" },
  { label: "Bell MT Std", family: "lib Bell MT Std" },
  { label: "Belwe Std", family: "lib Belwe Std" },
  { label: "Bembo Std", family: "lib Bembo Std" },
  { label: "Berling LT Std", family: "lib Berling LT Std" },
  { label: "Bermuda LP Std", family: "lib Bermuda LP Std" },
  { label: "Bernhard Modern Std", family: "lib Bernhard Modern Std" },
  { label: "Bernhard Std", family: "lib Bernhard Std" },
  { label: "Bickham Script Std", family: "lib Bickham Script Std" },
  { label: "Biffo MT Std", family: "lib Biffo MT Std" },
  { label: "Birch Std", family: "lib Birch Std" },
  { label: "Blackoak Std", family: "lib Blackoak Std" },
  { label: "Blue Island Std", family: "lib Blue Island Std" },
  { label: "Bodoni Std", family: "lib Bodoni Std" },
  { label: "Border Pi Std", family: "lib Border Pi Std" },
  { label: "Bossa Nova MVB Std", family: "lib Bossa Nova MVB Std" },
  { label: "Briem Akademi Std", family: "lib Briem Akademi Std" },
  { label: "Briem Script Std", family: "lib Briem Script Std" },
  { label: "Brioso Pro", family: "lib Brioso Pro" },
  { label: "Bruno JB Std", family: "lib Bruno JB Std" },
  { label: "Brush Script Std", family: "lib Brush Script Std" },
  { label: "Bulmer MT Std", family: "lib Bulmer MT Std" },
  { label: "Bundesbahn Pi Std", family: "lib Bundesbahn Pi Std" },
  { label: "Caflisch Script Pro", family: "lib Caflisch Script Pro" },
  { label: "Calcite Pro", family: "lib Calcite Pro" },
  { label: "Caliban Std", family: "lib Caliban Std" },
  { label: "Calvert MT Std", family: "lib Calvert MT Std" },
  { label: "Candida Std", family: "lib Candida Std" },
  { label: "Cantoria MT Std", family: "lib Cantoria MT Std" },
  { label: "Caravan LT Std", family: "lib Caravan LT Std" },
  { label: "Carolina LT Std", family: "lib Carolina LT Std" },
  { label: "Carta Std", family: "lib Carta Std" },
  { label: "Cascade Script LT Std", family: "lib Cascade Script LT Std" },
  { label: "Caslon 3 LT Std", family: "lib Caslon 3 LT Std" },
  { label: "Caslon 540 LT Std", family: "lib Caslon 540 LT Std" },
  { label: "Caslon Open Face LT Std", family: "lib Caslon Open Face LT Std" },
  { label: "Castellar MT Std", family: "lib Castellar MT Std" },
  { label: "Caxton Std", family: "lib Caxton Std" },
  { label: "Celestia Antiqua Std", family: "lib Celestia Antiqua Std" },
  { label: "Centaur MT Std", family: "lib Centaur MT Std" },
  { label: "Century Expanded LT Std", family: "lib Century Expanded LT Std" },
  { label: "Century Old Style Std", family: "lib Century Old Style Std" },
  { label: "Chaparral Pro", family: "lib Chaparral Pro" },
  { label: "Charlemagne Std", family: "lib Charlemagne Std" },
  { label: "Charme Std", family: "lib Charme Std" },
  { label: "Cheq Std", family: "lib Cheq Std" },
  { label: "Clairvaux LT Std", family: "lib Clairvaux LT Std" },
  { label: "Clarendon LT Std", family: "lib Clarendon LT Std" },
  { label: "Clearface Gothic LT Std", family: "lib Clearface Gothic LT Std" },
  { label: "Cloister Std", family: "lib Cloister Std" },
  { label: "Club Type Mercurius Std", family: "lib Club Type Mercurius Std" },
  { label: "Cochin LT Std", family: "lib Cochin LT Std" },
  { label: "Conga Brava Std", family: "lib Conga Brava Std" },
  { label: "Conga Brava Stencil Std", family: "lib Conga Brava Stencil Std" },
  { label: "Cooper Black Std", family: "lib Cooper Black Std" },
  { label: "Copal Std", family: "lib Copal Std" },
  { label: "Copperplate Gothic Std", family: "lib Copperplate Gothic Std" },
  { label: "Coriander Std", family: "lib Coriander Std" },
  { label: "Corona LT Std", family: "lib Corona LT Std" },
  { label: "Coronet LT Std", family: "lib Coronet LT Std" },
  { label: "Cottonwood Std", family: "lib Cottonwood Std" },
  { label: "Courier Std", family: "lib Courier Std" },
  { label: "Critter Std", family: "lib Critter Std" },
  { label: "Cronos Pro", family: "lib Cronos Pro" },
  { label: "Cutout Std", family: "lib Cutout Std" },
  { label: "Dante MT Std", family: "lib Dante MT Std" },
  { label: "Delphin LT Std", family: "lib Delphin LT Std" },
  { label: "DIN Std", family: "lib DIN Std" },
  { label: "Diotima LT Std", family: "lib Diotima LT Std" },
  { label: "Diskus LT Std", family: "lib Diskus LT Std" },
  { label: "Dom Casual Std", family: "lib Dom Casual Std" },
  { label: "Dorchester Script MT Std", family: "lib Dorchester Script MT Std" },
  { label: "Doric LT Std", family: "lib Doric LT Std" },
  { label: "Duc De Berry LT Std", family: "lib Duc De Berry LT Std" },
  { label: "Eccentric Std", family: "lib Eccentric Std" },
  { label: "Egyptienne F LT Std", family: "lib Egyptienne F LT Std" },
  { label: "Ehrhardt MT Std", family: "lib Ehrhardt MT Std" },
  { label: "Electra LT Std", family: "lib Electra LT Std" },
  { label: "Ellington MT Std", family: "lib Ellington MT Std" },
  { label: "Else NPL Std", family: "lib Else NPL Std" },
  { label: "Emmascript MVB Std", family: "lib Emmascript MVB Std" },
  { label: "Engravers LT Std", family: "lib Engravers LT Std" },
  { label: "Euro Mono Std", family: "lib Euro Mono Std" },
  { label: "Euro Sans Std", family: "lib Euro Sans Std" },
  { label: "Euro Serif Std", family: "lib Euro Serif Std" },
  { label: "European Pi Std", family: "lib European Pi Std" },
  { label: "Eurostile LT Std", family: "lib Eurostile LT Std" },
  { label: "Ex Ponto Pro", family: "lib Ex Ponto Pro" },
  { label: "Excelsior LT Std", family: "lib Excelsior LT Std" },
  { label: "Fairfield LT Std", family: "lib Fairfield LT Std" },
  { label: "Falstaff MT Std", family: "lib Falstaff MT Std" },
  { label: "Fette Fraktur LT Std", family: "lib Fette Fraktur LT Std" },
  { label: "Flood Std", family: "lib Flood Std" },
  { label: "Florens LP Std", family: "lib Florens LP Std" },
  { label: "Flyer LT Std", family: "lib Flyer LT Std" },
  { label: "Folio Std", family: "lib Folio Std" },
  { label: "Forte MT Std", family: "lib Forte MT Std" },
  { label: "Fournier MT Std", family: "lib Fournier MT Std" },
  { label: "Franklin Gothic Std", family: "lib Franklin Gothic Std" },
  { label: "Freestyle Script Std", family: "lib Freestyle Script Std" },
  { label: "Friz Quadrata Std", family: "lib Friz Quadrata Std" },
  { label: "Frutiger LT Std", family: "lib Frutiger LT Std" },
  { label: "Fusaka Std", family: "lib Fusaka Std" },
  { label: "Futura Std", family: "lib Futura Std" },
  { label: "Galahad Std", family: "lib Galahad Std" },
  { label: "Garamond 3 LT Std", family: "lib Garamond 3 LT Std" },
  { label: "Gazette LT Std", family: "lib Gazette LT Std" },
  { label: "Giddyup Std", family: "lib Giddyup Std" },
  { label: "Gill Floriated Caps MT Std", family: "lib Gill Floriated Caps MT Std" },
  { label: "Gill Sans Std", family: "lib Gill Sans Std" },
  { label: "Glypha LT Std", family: "lib Glypha LT Std" },
  { label: "Gothic Thirteen Std", family: "lib Gothic Thirteen Std" },
  { label: "Goudy Heavyface Std", family: "lib Goudy Heavyface Std" },
  { label: "Goudy Modern MT Std", family: "lib Goudy Modern MT Std" },
  { label: "Goudy Std", family: "lib Goudy Std" },
  { label: "Goudy Text MT Std", family: "lib Goudy Text MT Std" },
  { label: "Granjon LT Std", family: "lib Granjon LT Std" },
  { label: "Graphite Std", family: "lib Graphite Std" },
  { label: "Greymantle MVB Std", family: "lib Greymantle MVB Std" },
  { label: "Grotesque MT Std", family: "lib Grotesque MT Std" },
  { label: "Guardi LT Std", family: "lib Guardi LT Std" },
  { label: "Hardwood LP Std", family: "lib Hardwood LP Std" },
  { label: "Helvetica Inserat LT Std", family: "lib Helvetica Inserat LT Std" },
  { label: "Helvetica LT Std", family: "lib Helvetica LT Std" },
  { label: "Helvetica Neue LT Std", family: "lib Helvetica Neue LT Std" },
  { label: "Helvetica Rounded LT Std", family: "lib Helvetica Rounded LT Std" },
  { label: "Herculanum LT Std", family: "lib Herculanum LT Std" },
  { label: "Hiroshige Std", family: "lib Hiroshige Std" },
  { label: "Hobo Std", family: "lib Hobo Std" },
  { label: "Horley Old Style MT Std", family: "lib Horley Old Style MT Std" },
  { label: "Immi Five O Five Std", family: "lib Immi Five O Five Std" },
  { label: "Impact LT Std", family: "lib Impact LT Std" },
  { label: "Impressum Std", family: "lib Impressum Std" },
  { label: "Industria LT Std", family: "lib Industria LT Std" },
  { label: "Inflex MT Std", family: "lib Inflex MT Std" },
  { label: "Insignia LT Std", family: "lib Insignia LT Std" },
  { label: "Ironwood Std", family: "lib Ironwood Std" },
  { label: "Isabella Std", family: "lib Isabella Std" },
  { label: "Italia Std", family: "lib Italia Std" },
  { label: "Italian Old Style MT Std", family: "lib Italian Old Style MT Std" },
  { label: "ITC American Typewriter Std", family: "lib ITC American Typewriter Std" },
  { label: "ITC Anna Std", family: "lib ITC Anna Std" },
  { label: "ITC Avant Garde Gothic Std", family: "lib ITC Avant Garde Gothic Std" },
  { label: "ITC Beesknees Std", family: "lib ITC Beesknees Std" },
  { label: "ITC Benguiat Gothic Std", family: "lib ITC Benguiat Gothic Std" },
  { label: "ITC Benguiat Std", family: "lib ITC Benguiat Std" },
  { label: "ITC Berkeley Std", family: "lib ITC Berkeley Std" },
  { label: "ITC Bookman Std", family: "lib ITC Bookman Std" },
  { label: "ITC Caslon 224 Std", family: "lib ITC Caslon 224 Std" },
  { label: "ITC Century Handtooled Std", family: "lib ITC Century Handtooled Std" },
  { label: "ITC Century Std", family: "lib ITC Century Std" },
  { label: "ITC Cerigo Std", family: "lib ITC Cerigo Std" },
  { label: "ITC Cheltenham Handtooled Std", family: "lib ITC Cheltenham Handtooled Std" },
  { label: "ITC Cheltenham Std", family: "lib ITC Cheltenham Std" },
  { label: "ITC Clearface Std", family: "lib ITC Clearface Std" },
  { label: "ITC Cushing Std", family: "lib ITC Cushing Std" },
  { label: "ITC Eras Std", family: "lib ITC Eras Std" },
  { label: "ITC Esprit Std", family: "lib ITC Esprit Std" },
  { label: "ITC Fenice Std", family: "lib ITC Fenice Std" },
  { label: "ITC Flora Std", family: "lib ITC Flora Std" },
  { label: "ITC Franklin Gothic Std", family: "lib ITC Franklin Gothic Std" },
  { label: "ITC Galliard Std", family: "lib ITC Galliard Std" },
  { label: "ITC Garamond Handtooled Std", family: "lib ITC Garamond Handtooled Std" },
  { label: "ITC Garamond Std", family: "lib ITC Garamond Std" },
  { label: "ITC Giovanni Std", family: "lib ITC Giovanni Std" },
  { label: "ITC Goudy Sans Std", family: "lib ITC Goudy Sans Std" },
  { label: "ITC Highlander Std", family: "lib ITC Highlander Std" },
  { label: "ITC Isadora Std", family: "lib ITC Isadora Std" },
  { label: "ITC Kabel Std", family: "lib ITC Kabel Std" },
  { label: "ITC Korinna Std", family: "lib ITC Korinna Std" },
  { label: "ITC Leawood Std", family: "lib ITC Leawood Std" },
  { label: "ITC Legacy Sans Std", family: "lib ITC Legacy Sans Std" },
  { label: "ITC Legacy Serif Std", family: "lib ITC Legacy Serif Std" },
  { label: "ITC Lubalin Graph Std", family: "lib ITC Lubalin Graph Std" },
  { label: "ITC Machine Std", family: "lib ITC Machine Std" },
  { label: "ITC Mendoza Roman Std", family: "lib ITC Mendoza Roman Std" },
  { label: "ITC Mona Lisa Std", family: "lib ITC Mona Lisa Std" },
  { label: "ITC New Baskerville Std", family: "lib ITC New Baskerville Std" },
  { label: "ITC Novarese Std", family: "lib ITC Novarese Std" },
  { label: "ITC Officina Sans Std", family: "lib ITC Officina Sans Std" },
  { label: "ITC Officina Serif Std", family: "lib ITC Officina Serif Std" },
  { label: "ITC Ozwald Std", family: "lib ITC Ozwald Std" },
  { label: "ITC Quorum Std", family: "lib ITC Quorum Std" },
  { label: "ITC Serif Gothic Std", family: "lib ITC Serif Gothic Std" },
  { label: "ITC Slimbach Std", family: "lib ITC Slimbach Std" },
  { label: "ITC Souvenir Std", family: "lib ITC Souvenir Std" },
  { label: "ITC Stone Informal Std", family: "lib ITC Stone Informal Std" },
  { label: "ITC Stone Sans Std", family: "lib ITC Stone Sans Std" },
  { label: "ITC Stone Serif Std", family: "lib ITC Stone Serif Std" },
  { label: "ITC Symbol Std", family: "lib ITC Symbol Std" },
  { label: "ITC Tiepolo Std", family: "lib ITC Tiepolo Std" },
  { label: "ITC Tiffany Std", family: "lib ITC Tiffany Std" },
  { label: "ITC Usherwood Std", family: "lib ITC Usherwood Std" },
  { label: "ITC Veljovic Std", family: "lib ITC Veljovic Std" },
  { label: "ITC Zapf Chancery Std", family: "lib ITC Zapf Chancery Std" },
  { label: "ITC Zapf Dingbats Std", family: "lib ITC Zapf Dingbats Std" },
  { label: "Janson Text LT Std", family: "lib Janson Text LT Std" },
  { label: "Jimbo Std", family: "lib Jimbo Std" },
  { label: "Joanna MT Std", family: "lib Joanna MT Std" },
  { label: "Juniper Std", family: "lib Juniper Std" },
  { label: "Kabel LT Std", family: "lib Kabel LT Std" },
  { label: "Kaufmann Std", family: "lib Kaufmann Std" },
  { label: "Kepler Std Condensed Opticals", family: "lib Kepler Std Condensed Opticals" },
  { label: "Kepler Std Extended Opticals", family: "lib Kepler Std Extended Opticals" },
  { label: "Kepler Std Opticals", family: "lib Kepler Std Opticals" },
  { label: "Kepler Std SemiCond Opticals", family: "lib Kepler Std SemiCond Opticals" },
  { label: "Khaki Std", family: "lib Khaki Std" },
  { label: "Kigali Std", family: "lib Kigali Std" },
  { label: "Kinesis Std", family: "lib Kinesis Std" },
  { label: "Kino MT Std", family: "lib Kino MT Std" },
  { label: "Klang MT Std", family: "lib Klang MT Std" },
  { label: "Koch Antiqua LT Std", family: "lib Koch Antiqua LT Std" },
  { label: "Kolo LP Std", family: "lib Kolo LP Std" },
  { label: "Kompakt LT Std", family: "lib Kompakt LT Std" },
  { label: "Kuenstler Script LT Std", family: "lib Kuenstler Script LT Std" },
  { label: "Latin MT Std", family: "lib Latin MT Std" },
  { label: "Legault Std", family: "lib Legault Std" },
  { label: "Letter Gothic Std", family: "lib Letter Gothic Std" },
  { label: "Life LT Std", family: "lib Life LT Std" },
  { label: "LinoLetter Std", family: "lib LinoLetter Std" },
  { label: "Linoscript Std", family: "lib Linoscript Std" },
  { label: "Linotext Std", family: "lib Linotext Std" },
  { label: "Linotype Astrology Pi Std", family: "lib Linotype Astrology Pi Std" },
  { label: "Linotype Audio Pi Std", family: "lib Linotype Audio Pi Std" },
  { label: "Linotype Centennial Std", family: "lib Linotype Centennial Std" },
  { label: "Linotype Decoration Pi Std", family: "lib Linotype Decoration Pi Std" },
  { label: "Linotype Didot LT Std", family: "lib Linotype Didot LT Std" },
  { label: "Linotype Game Pi Std", family: "lib Linotype Game Pi Std" },
  { label: "Linotype Holiday Pi Std", family: "lib Linotype Holiday Pi Std" },
  { label: "Linotype Warning Pi Std", family: "lib Linotype Warning Pi Std" },
  { label: "Lithos Pro", family: "lib Lithos Pro" },
  { label: "Lucida Math Std", family: "lib Lucida Math Std" },
  { label: "Lucida Sans Std", family: "lib Lucida Sans Std" },
  { label: "Lucida Sans Typewriter Std", family: "lib Lucida Sans Typewriter Std" },
  { label: "Lucida Std", family: "lib Lucida Std" },
  { label: "Lucida Typewriter Std", family: "lib Lucida Typewriter Std" },
  { label: "Madrone Std", family: "lib Madrone Std" },
  { label: "Magnesium MVB Std", family: "lib Magnesium MVB Std" },
  { label: "Magnolia MVB Std", family: "lib Magnolia MVB Std" },
  { label: "Manito LP Std", family: "lib Manito LP Std" },
  { label: "Mathematical Pi LT Std", family: "lib Mathematical Pi LT Std" },
  { label: "Matura MT Std", family: "lib Matura MT Std" },
  { label: "Maximus LT Std", family: "lib Maximus LT Std" },
  { label: "Medici Script LT Std", family: "lib Medici Script LT Std" },
  { label: "Melior LT Std", family: "lib Melior LT Std" },
  { label: "Memphis LT Std", family: "lib Memphis LT Std" },
  { label: "Mercurius MT Std", family: "lib Mercurius MT Std" },
  { label: "Meridien LT Std", family: "lib Meridien LT Std" },
  { label: "Mesquite Std", family: "lib Mesquite Std" },
  { label: "Mezz Std", family: "lib Mezz Std" },
  { label: "MICR Std", family: "lib MICR Std" },
  { label: "Minion Pro", family: "lib Minion Pro" },
  { label: "Minion Std", family: "lib Minion Std" },
  { label: "Minister Std", family: "lib Minister Std" },
  { label: "Mistral Std", family: "lib Mistral Std" },
  { label: "Mojo Std", family: "lib Mojo Std" },
  { label: "Monoline Script MT Std", family: "lib Monoline Script MT Std" },
  { label: "Monotype Modern Std", family: "lib Monotype Modern Std" },
  { label: "Monotype Old Style MT Std", family: "lib Monotype Old Style MT Std" },
  { label: "Montara Std", family: "lib Montara Std" },
  { label: "Moonglow Std", family: "lib Moonglow Std" },
  { label: "Motter Corpus Std", family: "lib Motter Corpus Std" },
  { label: "Myriad Pro", family: "lib Myriad Pro" },
  { label: "Myriad Std", family: "lib Myriad Std" },
  { label: "Mythos Std", family: "lib Mythos Std" },
  { label: "National Code Pi Std", family: "lib National Code Pi Std" },
  { label: "Neue Hammer Unziale LT Std", family: "lib Neue Hammer Unziale LT Std" },
  { label: "Neuland LT Std", family: "lib Neuland LT Std" },
  { label: "Neuzeit S LT Std", family: "lib Neuzeit S LT Std" },
  { label: "New Aster LT Std", family: "lib New Aster LT Std" },
  { label: "New Berolina MT Std", family: "lib New Berolina MT Std" },
  { label: "New Caledonia LT Std", family: "lib New Caledonia LT Std" },
  { label: "New Century Schoolbook LT Std", family: "lib New Century Schoolbook LT Std" },
  { label: "News Gothic Std", family: "lib News Gothic Std" },
  { label: "Notre Dame LT Std", family: "lib Notre Dame LT Std" },
  { label: "Nueva Std", family: "lib Nueva Std" },
  { label: "Nuptial Script LT Std", family: "lib Nuptial Script LT Std" },
  { label: "Nyx Std", family: "lib Nyx Std" },
  { label: "Ocean Sans Std", family: "lib Ocean Sans Std" },
  { label: "OCRA Std", family: "lib OCRA Std" },
  { label: "OCRB Std", family: "lib OCRB Std" },
  { label: "Octavian MT Std", family: "lib Octavian MT Std" },
  { label: "Old Claude LP Std", family: "lib Old Claude LP Std" },
  { label: "Old Style 7 Std", family: "lib Old Style 7 Std" },
  { label: "Olympian LT Std", family: "lib Olympian LT Std" },
  { label: "Omnia LT Std", family: "lib Omnia LT Std" },
  { label: "Ondine LT Std", family: "lib Ondine LT Std" },
  { label: "Onyx MT Std", family: "lib Onyx MT Std" },
  { label: "Optima LT Std", family: "lib Optima LT Std" },
  { label: "Orator Std", family: "lib Orator Std" },
  { label: "Organica GMM Std", family: "lib Organica GMM Std" },
  { label: "Origami Std", family: "lib Origami Std" },
  { label: "Ouch Std", family: "lib Ouch Std" },
  { label: "Palace Script MT Std", family: "lib Palace Script MT Std" },
  { label: "Palatino LT Std", family: "lib Palatino LT Std" },
  { label: "Parisian Std", family: "lib Parisian Std" },
  { label: "Park Avenue Std", family: "lib Park Avenue Std" },
  { label: "Peignot LT Std", family: "lib Peignot LT Std" },
  { label: "Penumbra Flare Std", family: "lib Penumbra Flare Std" },
  { label: "Penumbra Half Serif Std", family: "lib Penumbra Half Serif Std" },
  { label: "Penumbra Sans Std", family: "lib Penumbra Sans Std" },
  { label: "Penumbra Serif Std", family: "lib Penumbra Serif Std" },
  { label: "Pepita MT Std", family: "lib Pepita MT Std" },
  { label: "Pepperwood Std", family: "lib Pepperwood Std" },
  { label: "Perpetua Std", family: "lib Perpetua Std" },
  { label: "Photina MT Std", family: "lib Photina MT Std" },
  { label: "Plantin Std", family: "lib Plantin Std" },
  { label: "PMN Caecilia LT Std", family: "lib PMN Caecilia LT Std" },
  { label: "Poetica Std", family: "lib Poetica Std" },
  { label: "Pompeia Std", family: "lib Pompeia Std" },
  { label: "Pompeijana LT Std", family: "lib Pompeijana LT Std" },
  { label: "Ponderosa Std", family: "lib Ponderosa Std" },
  { label: "Poplar Std", family: "lib Poplar Std" },
  { label: "Postino Std", family: "lib Postino Std" },
  { label: "Present LT Std", family: "lib Present LT Std" },
  { label: "Prestige Elite Std", family: "lib Prestige Elite Std" },
  { label: "Quake Std", family: "lib Quake Std" },
  { label: "Rad Std", family: "lib Rad Std" },
  { label: "Raleigh LT Std", family: "lib Raleigh LT Std" },
  { label: "Raphael Std", family: "lib Raphael Std" },
  { label: "Reliq Std", family: "lib Reliq Std" },
  { label: "Reporter LT Std", family: "lib Reporter LT Std" },
  { label: "Revue Std", family: "lib Revue Std" },
  { label: "Rockwell Std", family: "lib Rockwell Std" },
  { label: "Romic Std", family: "lib Romic Std" },
  { label: "Rosewood Std", family: "lib Rosewood Std" },
  { label: "Rotation LT Std", family: "lib Rotation LT Std" },
  { label: "Ruling Script LT Std", family: "lib Ruling Script LT Std" },
  { label: "Runic MT Std", family: "lib Runic MT Std" },
  { label: "Russell Oblique Std", family: "lib Russell Oblique Std" },
  { label: "Rusticana LT Std", family: "lib Rusticana LT Std" },
  { label: "Ruzicka Freehand LT Std", family: "lib Ruzicka Freehand LT Std" },
  { label: "Sabon LT Std", family: "lib Sabon LT Std" },
  { label: "Salernomi J", family: "lib Salernomi J" },
  { label: "San Marco LT Std", family: "lib San Marco LT Std" },
  { label: "Sanvito Pro", family: "lib Sanvito Pro" },
  { label: "Sassafras Std", family: "lib Sassafras Std" },
  { label: "Scotch Roman MT Std", family: "lib Scotch Roman MT Std" },
  { label: "Script MT Std", family: "lib Script MT Std" },
  { label: "Serifa Std", family: "lib Serifa Std" },
  { label: "Serlio LT Std", family: "lib Serlio LT Std" },
  { label: "Shelley Script LT Std", family: "lib Shelley Script LT Std" },
  { label: "Sho LT Std", family: "lib Sho LT Std" },
  { label: "Shuriken Boy Std", family: "lib Shuriken Boy Std" },
  { label: "Silentium Pro", family: "lib Silentium Pro" },
  { label: "Simoncini Garamond Std", family: "lib Simoncini Garamond Std" },
  { label: "Smaragd LT Std", family: "lib Smaragd LT Std" },
  { label: "Snell Roundhand LT Std", family: "lib Snell Roundhand LT Std" },
  { label: "Sonata Std", family: "lib Sonata Std" },
  { label: "Spartan LT Std", family: "lib Spartan LT Std" },
  { label: "Spectrum MT Std", family: "lib Spectrum MT Std" },
  { label: "Spring LP Std", family: "lib Spring LP Std" },
  { label: "Spumoni LP Std", family: "lib Spumoni LP Std" },
  { label: "Stempel Garamond LT Std", family: "lib Stempel Garamond LT Std" },
  { label: "Stempel Schneidler Std", family: "lib Stempel Schneidler Std" },
  { label: "Stencil Std", family: "lib Stencil Std" },
  { label: "Strayhorn MT Std", family: "lib Strayhorn MT Std" },
  { label: "Strumpf Std", family: "lib Strumpf Std" },
  { label: "Studz Std", family: "lib Studz Std" },
  { label: "Symbol Std", family: "lib Symbol Std" },
  { label: "Syntax LT Std", family: "lib Syntax LT Std" },
  { label: "Tekton Pro", family: "lib Tekton Pro" },
  { label: "Tempo Std", family: "lib Tempo Std" },
  { label: "Times Europa LT Std", family: "lib Times Europa LT Std" },
  { label: "Times LT Std", family: "lib Times LT Std" },
  { label: "Times New Roman MT Std", family: "lib Times New Roman MT Std" },
  { label: "Times Ten LT Std", family: "lib Times Ten LT Std" },
  { label: "Toolbox Std", family: "lib Toolbox Std" },
  { label: "Trade Gothic LT Std", family: "lib Trade Gothic LT Std" },
  { label: "Trajan Pro", family: "lib Trajan Pro" },
  { label: "Trump Mediaeval LT Std", family: "lib Trump Mediaeval LT Std" },
  { label: "Umbra Std", family: "lib Umbra Std" },
  { label: "Univers LT Std", family: "lib Univers LT Std" },
  { label: "Universal Std", family: "lib Universal Std" },
  { label: "University Roman Std", family: "lib University Roman Std" },
  { label: "Utopia Std", family: "lib Utopia Std" },
  { label: "VAG Rounded Std", family: "lib VAG Rounded Std" },
  { label: "Vectora LT Std", family: "lib Vectora LT Std" },
  { label: "Versailles LT Std", family: "lib Versailles LT Std" },
  { label: "Verve Std", family: "lib Verve Std" },
  { label: "Viva Std", family: "lib Viva Std" },
  { label: "Voluta Script Pro", family: "lib Voluta Script Pro" },
  { label: "Warnock Pro", family: "lib Warnock Pro" },
  { label: "Waters Titling Pro", family: "lib Waters Titling Pro" },
  { label: "WebType Pro", family: "lib WebType Pro" },
  { label: "Weidemann Std", family: "lib Weidemann Std" },
  { label: "Weiss Std", family: "lib Weiss Std" },
  { label: "Wendy LP Std", family: "lib Wendy LP Std" },
  { label: "Wiesbaden Swing LT Std", family: "lib Wiesbaden Swing LT Std" },
  { label: "Wilhelm Klingspor Gothic LT Std", family: "lib Wilhelm Klingspor Gothic LT Std" },
  { label: "Wilke LT Std", family: "lib Wilke LT Std" },
  { label: "Willow Std", family: "lib Willow Std" },
  { label: "Wittenberger Fraktur MT Std", family: "lib Wittenberger Fraktur MT Std" },
  { label: "Zebrawood Std", family: "lib Zebrawood Std" },
  { label: "Zipty Do Std", family: "lib Zipty Do Std" },
]
